name: Check, test and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.2.2

      - name: Check repo
        run: cd src
        run: ls -la
        
     # - name: Setup php
     #   uses: shivammathur/setup-php@2.34.1
     #   with:
     #     php-version: '8.4'
      
# install mariadb
     # - name: Setup mariadb
     #   run: sudo apt-get install mariadb-server mariadb-client
     # - name: Secure the Installation mariadb
     #   run: sudo mariadb-secure-installation     
      
#      - name: Install dependencies
#        run: composer install --prefer-dist --no-progress --no-sugget
#
#      - name: Setup laravel
#        run: |
#          cp .env.example .env
#          php artisan config:clear
#          php artisan cache:clear
#          php artisan key:generate
#
#      - name: Check PHP syntax errors
#        uses: overtrue/phplint@9.6.2      
#  
#      - name: Composer audit
#        run: composer audit
#
#      - name: Composer validate
#        run: composer validate --no-check-all --strict
#
#      - name: Setup nodejs
#        uses: actions\setup-node@v4
#        with:
#          node-version: '22.16.0'
#
#      - name: Install nodejs dependencies
#        run: npm install
#
#      - name: Run tests
#        run: run ./vendor/bin/phpunit --colors=always
#
#      - name: Run phpstan
#        run: ./vendor/bin/phpstan analyse
    
